// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: youversion.red.movies.api.model.common.UtmMedium.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Auto-Generated from OpenAPI Spec

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Youversion_Red_Movies_Api_Model_Common_UtmMedium: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case unsupportedPlaceholder // = 0
  case share // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .unsupportedPlaceholder
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unsupportedPlaceholder
    case 1: self = .share
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unsupportedPlaceholder: return 0
    case .share: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Youversion_Red_Movies_Api_Model_Common_UtmMedium: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Youversion_Red_Movies_Api_Model_Common_UtmMedium] = [
    .unsupportedPlaceholder,
    .share,
  ]
}

#endif  // swift(>=4.2)

#if swift(>=5.5) && canImport(_Concurrency)
extension Youversion_Red_Movies_Api_Model_Common_UtmMedium: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Youversion_Red_Movies_Api_Model_Common_UtmMedium: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UTM_MEDIUM_UNSUPPORTED_PLACEHOLDER"),
    1: .same(proto: "SHARE"),
  ]
}
