name: Swift Package Tests

on: [pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      - name: Display Swift and Xcode versions
        run: |
          swift --version
          xcodebuild -version

      # Build the Swift package
      - name: Build
        run: swift build

      # Run unit tests
      - name: Run tests
        run: xcodebuild -scheme YouVersionPlatform-Package \
               -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
               clean test