name: Swift Package Tests

on: [pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up the Swift environment
      - uses: swift-actions/setup-swift
        with:
          swift-version: "5.9" # Specify the Swift version you want to use

      # Build the Swift package
      - name: Build
        run: swift build

      # Run unit tests
      - name: Run tests
        run: swift test